[package]
name = "twitch_integration"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
raylib = "5.5.1"
reqwest = { version = "0.12.15", features = ["json"] }
serde_json = "1.0.140"
tokio = { version = "*", features = ["full"] }
url = "*"
